# Generated by Django 4.1.2 on 2022-12-03 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_project_manage_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis_project_manage',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thesis_project_manage_App.project_type'),
        ),
        migrations.AlterField(
            model_name='thesis_project_manage',
            name='thesis_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thesis_project_manage_App.thesis_type'),
        ),
    ]
