# Generated by Django 4.1.2 on 2022-11-07 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_dashboard_App', '0004_auth_profile_customer_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/backend/teacher_profile/')),
            ],
        ),
    ]
