# Generated by Django 4.1.2 on 2022-10-24 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_App', '0003_remove_student_profile_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Student_profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
