# Generated by Django 4.1.2 on 2022-10-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_App', '0004_alter_student_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
