# Generated by Django 4.1.2 on 2022-11-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_dashboard_App', '0003_alter_user_student_id_alter_user_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_profile_customer',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
