# Generated by Django 4.1.2 on 2022-12-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_dashboard_App', '0004_auth_profile_customer_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
